// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using GHLearning.ThreeLayer.Repository.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace GHLearning.ThreeLayer.Repository.Entities.Configurations
{
    public partial class UserStatusConfiguration : IEntityTypeConfiguration<UserStatus>
    {
        public void Configure(EntityTypeBuilder<UserStatus> entity)
        {
            entity.HasKey(e => e.UserId).HasName("PRIMARY");

            entity
                .ToTable("user_statuses", tb => tb.HasComment("使用者狀態"))
                .UseCollation("utf8mb4_general_ci");

            entity.Property(e => e.UserId)
                .HasMaxLength(15)
                .HasComment("使用者主表識別碼")
                .HasColumnName("user_id");
            entity.Property(e => e.Status)
                .HasComment("狀態")
                .HasColumnName("status");

            entity.HasOne(d => d.User).WithOne(p => p.UserStatus)
                .HasForeignKey<UserStatus>(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_user_statuses_users");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<UserStatus> entity);
    }
}
