// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using GHLearning.ThreeLayer.Repository.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace GHLearning.ThreeLayer.Repository.Entities.Configurations
{
    public partial class UserLogConfiguration : IEntityTypeConfiguration<UserLog>
    {
        public void Configure(EntityTypeBuilder<UserLog> entity)
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity
                .ToTable("user_logs")
                .UseCollation("utf8mb4_general_ci");

            entity.HasIndex(e => e.UserId, "fk_user_log_user");

            entity.Property(e => e.Id)
                .HasComment("識別碼")
                .HasColumnName("id")
                .UseCollation("ascii_general_ci")
                .HasCharSet("ascii");
            entity.Property(e => e.CreatedAt)
                .HasComment("日誌時間")
                .HasColumnType("datetime")
                .HasColumnName("created_at");
            entity.Property(e => e.Description)
                .HasMaxLength(255)
                .HasComment("描述")
                .HasColumnName("description");
            entity.Property(e => e.Event)
                .HasMaxLength(63)
                .HasComment("事件")
                .HasColumnName("event");
            entity.Property(e => e.UserId)
                .HasMaxLength(15)
                .HasComment("使用者識別碼")
                .HasColumnName("user_id");

            entity.HasOne(d => d.User).WithMany(p => p.UserLogs)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_user_logs_users");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<UserLog> entity);
    }
}
