// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using GHLearning.ThreeLayer.Repository.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace GHLearning.ThreeLayer.Repository.Entities.Configurations
{
    public partial class UserConfiguration : IEntityTypeConfiguration<User>
    {
        public void Configure(EntityTypeBuilder<User> entity)
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity
                .ToTable("users", tb => tb.HasComment("使用者主表"))
                .UseCollation("utf8mb4_general_ci");

            entity.HasIndex(e => e.Account, "uq_users_account").IsUnique();

            entity.Property(e => e.Id)
                .HasMaxLength(15)
                .HasComment("識別碼")
                .HasColumnName("id");
            entity.Property(e => e.Account)
                .HasMaxLength(31)
                .HasComment("帳號名稱")
                .HasColumnName("account");
            entity.Property(e => e.CreatedAt)
                .HasComment("創建時間")
                .HasColumnType("datetime")
                .HasColumnName("created_at");
            entity.Property(e => e.Password)
                .HasMaxLength(255)
                .HasComment("密碼")
                .HasColumnName("password");
            entity.Property(e => e.UpdatedAt)
                .HasComment("最後更新時間")
                .HasColumnType("datetime")
                .HasColumnName("updated_at");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<User> entity);
    }
}
