// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using GHLearning.ThreeLayer.Repositories.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace GHLearning.ThreeLayer.Repositories.Entities.Configurations
{
    public partial class UserVipLevelConfiguration : IEntityTypeConfiguration<UserVipLevel>
    {
        public void Configure(EntityTypeBuilder<UserVipLevel> entity)
        {
            entity.HasKey(e => e.UserId).HasName("PRIMARY");

            entity.ToTable("user_vip_levels", tb => tb.HasComment("使用者等級"));

            entity.Property(e => e.UserId)
                .HasMaxLength(15)
                .HasComment("使用者主表識別碼")
                .HasColumnName("user_id");
            entity.Property(e => e.VipLevel)
                .HasComment("等級")
                .HasColumnType("tinyint(3) unsigned")
                .HasColumnName("vip_level");

            entity.HasOne(d => d.User).WithOne(p => p.UserVipLevel)
                .HasForeignKey<UserVipLevel>(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_user_vip_levels_users");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<UserVipLevel> entity);
    }
}
