// <auto-generated />
using System;
using GHLearning.ThreeLayer.Migrations.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GHLearning.ThreeLayer.Migrations.Migrations
{
    [DbContext(typeof(SampleContext))]
    partial class SampleContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("GHLearning.ThreeLayer.Migrations.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("id")
                        .HasComment("識別碼");

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasMaxLength(31)
                        .HasColumnType("varchar(31)")
                        .HasColumnName("account")
                        .HasComment("帳號名稱");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasComment("創建時間");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password")
                        .HasComment("密碼");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasComment("最後更新時間");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Account" }, "uq_users_account")
                        .IsUnique();

                    b.ToTable("users", null, t =>
                        {
                            t.HasComment("使用者主表");
                        });

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_general_ci");
                });

            modelBuilder.Entity("GHLearning.ThreeLayer.Migrations.Entities.UserInfo", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("user_id")
                        .HasComment("使用者主表識別碼");

                    b.Property<string>("NickName")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("varchar(63)")
                        .HasColumnName("nick_name")
                        .HasComment("暱稱");

                    b.HasKey("UserId")
                        .HasName("PRIMARY");

                    b.ToTable("user_infos", null, t =>
                        {
                            t.HasComment("使用者資訊");
                        });

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_general_ci");
                });

            modelBuilder.Entity("GHLearning.ThreeLayer.Migrations.Entities.UserLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id")
                        .HasComment("識別碼")
                        .UseCollation("ascii_general_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("Id"), "ascii");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasComment("日誌時間");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("description")
                        .HasComment("描述");

                    b.Property<string>("Event")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("varchar(63)")
                        .HasColumnName("event")
                        .HasComment("事件");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("user_id")
                        .HasComment("使用者識別碼");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "UserId" }, "fk_user_log_user");

                    b.ToTable("user_logs", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_general_ci");
                });

            modelBuilder.Entity("GHLearning.ThreeLayer.Migrations.Entities.UserStatus", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("user_id")
                        .HasComment("使用者主表識別碼");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("status")
                        .HasComment("狀態");

                    b.HasKey("UserId")
                        .HasName("PRIMARY");

                    b.ToTable("user_statuses", null, t =>
                        {
                            t.HasComment("使用者狀態");
                        });

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_general_ci");
                });

            modelBuilder.Entity("GHLearning.ThreeLayer.Migrations.Entities.UserVipLevel", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("user_id")
                        .HasComment("使用者主表識別碼");

                    b.Property<byte>("VipLevel")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("vip_level")
                        .HasComment("等級");

                    b.HasKey("UserId")
                        .HasName("PRIMARY");

                    b.ToTable("user_vip_levels", null, t =>
                        {
                            t.HasComment("使用者等級");
                        });

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_general_ci");
                });

            modelBuilder.Entity("GHLearning.ThreeLayer.Migrations.Entities.UserInfo", b =>
                {
                    b.HasOne("GHLearning.ThreeLayer.Migrations.Entities.User", "User")
                        .WithOne("UserInfo")
                        .HasForeignKey("GHLearning.ThreeLayer.Migrations.Entities.UserInfo", "UserId")
                        .IsRequired()
                        .HasConstraintName("fk_user_infos_users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GHLearning.ThreeLayer.Migrations.Entities.UserLog", b =>
                {
                    b.HasOne("GHLearning.ThreeLayer.Migrations.Entities.User", "User")
                        .WithMany("UserLogs")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("fk_user_logs_users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GHLearning.ThreeLayer.Migrations.Entities.UserStatus", b =>
                {
                    b.HasOne("GHLearning.ThreeLayer.Migrations.Entities.User", "User")
                        .WithOne("UserStatus")
                        .HasForeignKey("GHLearning.ThreeLayer.Migrations.Entities.UserStatus", "UserId")
                        .IsRequired()
                        .HasConstraintName("fk_user_statuses_users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GHLearning.ThreeLayer.Migrations.Entities.UserVipLevel", b =>
                {
                    b.HasOne("GHLearning.ThreeLayer.Migrations.Entities.User", "User")
                        .WithOne("UserVipLevel")
                        .HasForeignKey("GHLearning.ThreeLayer.Migrations.Entities.UserVipLevel", "UserId")
                        .IsRequired()
                        .HasConstraintName("fk_user_vip_levels_users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GHLearning.ThreeLayer.Migrations.Entities.User", b =>
                {
                    b.Navigation("UserInfo");

                    b.Navigation("UserLogs");

                    b.Navigation("UserStatus");

                    b.Navigation("UserVipLevel");
                });
#pragma warning restore 612, 618
        }
    }
}
