// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using GHLearning.ThreeLayer.Migrations.Entities.Configurations;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
#nullable enable

namespace GHLearning.ThreeLayer.Migrations.Entities;

public partial class SampleContext : DbContext
{
    public SampleContext(DbContextOptions<SampleContext> options)
        : base(options)
    {
    }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<UserInfo> UserInfos { get; set; }

    public virtual DbSet<UserLog> UserLogs { get; set; }

    public virtual DbSet<UserStatus> UserStatuses { get; set; }

    public virtual DbSet<UserVipLevel> UserVipLevels { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder
            .UseCollation("utf8mb4_0900_ai_ci")
            .HasCharSet("utf8mb4");

        modelBuilder.ApplyConfiguration(new Configurations.UserConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.UserInfoConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.UserLogConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.UserStatusConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.UserVipLevelConfiguration());
        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
