// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace GHLearning.ThreeLayer.Repositories.Entities;

/// <summary>
/// 使用者等級
/// </summary>
public partial class UserVipLevel
{
    /// <summary>
    /// 使用者主表識別碼
    /// </summary>
    public string UserId { get; set; } = null!;

    /// <summary>
    /// 等級
    /// </summary>
    public byte VipLevel { get; set; }

    public virtual User User { get; set; } = null!;
}