// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace GHLearning.ThreeLayer.Migrations.Entities;

/// <summary>
/// 使用者狀態
/// </summary>
public partial class UserStatus
{
    /// <summary>
    /// 使用者主表識別碼
    /// </summary>
    public string UserId { get; set; } = null!;

    /// <summary>
    /// 狀態
    /// </summary>
    public byte Status { get; set; }

    public virtual User User { get; set; } = null!;
}